# Generated by Django 2.0.2 on 2019-03-30 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_daynumber_userip_visitnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daynumber',
            name='day',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='日期', verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='count',
            field=models.IntegerField(default=0, help_text='访问次数', verbose_name='访问次数'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='end_point',
            field=models.CharField(default='/', help_text='访问端点', max_length=30, verbose_name='访问端点'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='ip',
            field=models.CharField(help_text='ip地址', max_length=30, verbose_name='IP 地址'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='ip_addr',
            field=models.CharField(help_text='ip地理位置', max_length=30, verbose_name='IP 地理位置'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='出生年月', null=True, verbose_name='出生年月'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='邮箱', max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', help_text='性别', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='电话', max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, help_text='姓名', max_length=30, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(help_text='验证码', max_length=10, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='mobile',
            field=models.CharField(blank=True, help_text='电话', max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='visitnumber',
            name='count',
            field=models.IntegerField(default=0, help_text='网站访问总次数', verbose_name='网站访问总次数'),
        ),
    ]
