# Generated by Django 2.0.2 on 2019-03-14 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_indexad'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
    ]
