# Generated by Django 2.0.2 on 2019-03-18 03:15

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190314_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=1024000000000, verbose_name='内容'),
        ),
    ]
